#pragma once

#define UNICODE_KEY_MAC KC_LEFT_ALT
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_KEY_WINC KC_RIGHT_ALT

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define OS_SWITCH_UNICODE
